In order to use the tradingstrategy package, you need to:
- create a new conda environment equipped with python=3.10 
    - conda create --name ENV_NAME python=3.10
- activate it
    - conda activate ENV_NAME
- install tradingstrategy using pip
    - pip install "trading-strategy[direct-feed]"
- export the TRADING_STRATEGY_API_KEY environment variable. The key can be obtained by signing up to tradingstrategy.ai

In [69]:
import os
# Set environment variable for this script and any subprocesses
os.environ["TRADING_STRATEGY_API_KEY"] = "secret-token:tradingstrategy-24eaf8956529ba888ce7a6a0e88913f3d95d1ece83dafb019fbe0332224ce0ad"
# Example: running a command that uses the environment variable
os.system('echo $TRADING_STRATEGY_API_KEY')

secret-token:tradingstrategy-24eaf8956529ba888ce7a6a0e88913f3d95d1ece83dafb019fbe0332224ce0ad

0

The following are some simple functions to get information about pairs from the pairs dataframe downloaded from https://tradingstrategy.ai/trading-view/backtesting?ref=trading-strategy.ghost.io

In [70]:
import pandas as pd

# Search for the pair with the given token symbols
def search_pair(token0_symbol, token1_symbol):
    # search for the pair with the given token symbols regardless the order
    pair_f = pairs[(pairs['token0_symbol'] == token0_symbol) & (pairs['token1_symbol'] == token1_symbol)]
    pair_r = pairs[(pairs['token0_symbol'] == token1_symbol) & (pairs['token1_symbol'] == token0_symbol)]
    # concatenate the two results
    pair = pd.concat([pair_f, pair_r])
    # sort the result by buy_volume_all_time + sell_volume_all_time
    pair = pair.sort_values(by=['buy_volume_all_time', 'sell_volume_all_time'], ascending=False)
    return pair

# Search for the pairs on the given exchange
def search_exchange(exchange):
    return pairs[pairs['dex_type'] == exchange]

# Search by pair id
def search_pair_by_id(pair_id):
    return pairs[pairs['pair_id'] == pair_id]

In [71]:
# Read the parquet file containing all the pairs
pairs = pd.read_parquet('/home/danielemdn/Documents/repositories/data/DeFi/pair-universe')
print(f'Features of the pairs parquet dataframe:\n\t{pairs.columns}')

# Search for the pair with the given token symbols
pair = search_pair('WETH', 'USDC')
pair

Features of the pairs parquet dataframe:
	Index(['pair_id', 'chain_id', 'exchange_id', 'address', 'token0_address',
       'token1_address', 'token0_symbol', 'token1_symbol', 'dex_type',
       'base_token_symbol', 'quote_token_symbol', 'token0_decimals',
       'token1_decimals', 'exchange_slug', 'exchange_address', 'pair_slug',
       'first_swap_at_block_number', 'last_swap_at_block_number',
       'first_swap_at', 'last_swap_at', 'flag_inactive',
       'flag_blacklisted_manually', 'flag_unsupported_quote_token',
       'flag_unknown_exchange', 'fee', 'buy_count_all_time',
       'sell_count_all_time', 'buy_volume_all_time', 'sell_volume_all_time',
       'buy_count_30d', 'sell_count_30d', 'buy_volume_30d', 'sell_volume_30d',
       'buy_tax', 'transfer_tax', 'sell_tax', 'exchange_name'],
      dtype='object')

,pair_id,chain_id,exchange_id,address,token0_address,token1_address,token0_symbol,token1_symbol,dex_type,base_token_symbol,...,buy_volume_all_time,sell_volume_all_time,buy_count_30d,sell_count_30d,buy_volume_30d,sell_volume_30d,buy_tax,transfer_tax,sell_tax,exchange_name
158716,2991521,42161,4338,0xc31e54c7a869b9fcbecc14363cf510d1c41fa443,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,WETH,USDC,uniswap_v3,WETH,...,2.606096e+10,2.601838e+10,0.0,0.0,7.527613e+08,7.596357e+08,NaN,NaN,NaN,None
0,1,1,1,0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,USDC,WETH,uniswap_v2,WETH,...,2.259838e+10,2.240351e+10,48605.0,41009.0,1.415643e+08,1.458504e+08,0.0,0.0,0.0,None
1413,9261,1,22,0x397ff1542f962076d0bfe58ea045ffa2d347aca0,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,USDC,WETH,uniswap_v2,WETH,...,1.571117e+10,1.556137e+10,11577.0,10820.0,1.347286e+07,1.408837e+07,0.0,0.0,0.0,None
13405,93756,137,360,0x853ee4b2a13f8a742d64c8f088be7ba2131f670d,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,USDC,WETH,uniswap_v2,WETH,...,3.909363e+09,3.903740e+09,7622.0,6882.0,2.907419e+06,3.031317e+06,0.0,0.0,0.0,None
156785,2949365,42161,4122,0x905dfcd5649217c42684f23958568e533c711aa3,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,WETH,USDC,uniswap_v2,WETH,...,2.118679e+09,2.118971e+09,12073.0,10831.0,1.833710e+06,1.878153e+06,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222292,3544423,42161,5340,0xa825cbce55b46c7a9dfc6a8376faf707d432fc9f,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8,WETH,USDC,uniswap_v2,WETH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
14519,100103,137,455,0xc3e32d187bcb4da7594d23f8aca65613449bb3ea,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,USDC,WETH,uniswap_v2,WETH,...,NaN,NaN,NaN,NaN,NaN,NaN,997.0,997.0,997.0,None
15082,103365,137,493,0xf758c3ae5b665390ea00366200d5eb6858078e48,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,USDC,WETH,uniswap_v2,WETH,...,NaN,NaN,NaN,NaN,NaN,NaN,997.0,997.0,997.0,None
125061,2621713,137,601,0x0ecb5d668cc6ab450738b7f605de24c3d7fdbcac,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,USDC,WETH,uniswap_v2,WETH,...,NaN,NaN,NaN,NaN,NaN,NaN,997.0,997.0,997.0,None
126888,2665319,137,3612,0xcd2c5b223fa8e9a26113eb434fea79748c4d8251,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,USDC,WETH,uniswap_v2,WETH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [72]:
from tradingstrategy.client import Client
from tradingstrategy.trade import Trade
from tradingstrategy.timebucket import TimeBucket
from datetime import datetime

# Create a client
client = Client.create_jupyter_client()

Started Trading Strategy in Jupyter notebook environment, configuration is stored in /home/danielemdn/.tradingstrategy

In [76]:
# Fetch the candles for the given pair
delta_t = TimeBucket.d1
start_time = datetime(2024, 1, 30, 00, 00, 00)  # 0:00:00 on January 1, 2024
end_time = datetime(2024, 2, 25, 00, 00, 00)    # 17:00:00 on January 1, 2024


candle_pairs = client.fetch_candles_by_pair_ids([2991521, 1], bucket=delta_t, start_time=start_time, end_time=end_time, max_bytes=None, progress_bar_description=None)
candle_pairs

,timestamp,open,high,low,close,volume,exchange_rate,buys,sells,buy_volume,sell_volume,pair_id,start_block,end_block,avg
timestamp,,,,,,,,,,,,,,,
2024-01-30,2024-01-30,2317.267744,2384.257651,2303.505101,2342.044160,4.863735e+06,1.0,1174.0,1133.0,2.567587e+06,2.296148e+06,1,19115614,19122756,NaN
2024-01-31,2024-01-31,2342.045420,2345.089105,2267.864690,2277.471000,5.711551e+06,1.0,1322.0,1250.0,2.512496e+06,3.199055e+06,1,19122764,19129888,NaN
2024-02-01,2024-02-01,2277.542740,2308.605910,2246.780619,2297.139937,3.727654e+06,1.0,1119.0,945.0,1.973031e+06,1.754623e+06,1,19129892,19137011,NaN
2024-02-02,2024-02-02,2297.180343,2324.426035,2286.669443,2301.446531,4.583016e+06,1.0,1254.0,1011.0,2.318174e+06,2.264842e+06,1,19137018,19144136,NaN
2024-02-03,2024-02-03,2301.446702,2325.080586,2297.235543,2298.912883,2.632534e+06,1.0,1011.0,886.0,1.304607e+06,1.327927e+06,1,19144139,19151246,NaN
2024-02-04,2024-02-04,2298.891561,2309.159750,2273.804065,2287.561760,2.748733e+06,1.0,1149.0,1098.0,1.315266e+06,1.433467e+06,1,19151257,19158366,NaN
2024-02-05,2024-02-05,2287.550221,2330.580419,2274.380686,2294.321250,3.115433e+06,1.0,1063.0,796.0,1.596501e+06,1.518931e+06,1,19158372,19165489,NaN
2024-02-06,2024-02-06,2294.747472,2384.624590,2294.375878,2380.005810,4.682825e+06,1.0,1205.0,914.0,2.802433e+06,1.880391e+06,1,19165491,19172612,NaN
2024-02-07,2024-02-07,2379.903767,2437.849560,2359.369638,2429.050523,3.911018e+06,1.0,1084.0,861.0,2.216658e+06,1.694360e+06,1,19172627,19179745,NaN
2024-02-08,2024-02-08,2429.029063,2454.344799,2416.961205,2426.832534,3.983770e+06,1.0,997.0,833.0,1.983257e+06,2.000513e+06,1,19179753,19186846,NaN
2024-02-09,2024-02-09,2426.841442,2516.817933,2424.313244,2494.491086,5.289111e+06,1.0,950.0,706.0,3.000712e+06,2.288399e+06,1,19186875,19193998,NaN
2024-02-10,2024-02-10,2493.790080,2512.032769,2480.785691,2502.014567,3.797183e+06,1.0,1037.0,828.0,1.940316e+06,1.856866e+06,1,19194010,19201112,NaN
2024-02-11,2024-02-11,2502.007623,2533.701930,2500.094272,2504.227694,3.565296e+06,1.0,1102.0,868.0,1.796754e+06,1.768542e+06,1,19201123,19208236,NaN
2024-02-12,2024-02-12,2504.352344,2751.207806,2478.251413,2656.863003,1.169651e+07,1.0,1023.0,830.0,6.633200e+06,5.063307e+06,1,19208245,19215376,NaN
2024-02-13,2024-02-13,2656.912803,2683.438816,2600.319242,2639.328844,7.991301e+06,1.0,1522.0,1025.0,3.913618e+06,4.077683e+06,1,19215378,19222501,NaN
2024-02-14,2024-02-14,2639.343489,2784.017625,2626.073439,2779.301892,7.023278e+06,1.0,1550.0,1100.0,4.211975e+06,2.811302e+06,1,19222514,19229624,NaN
2024-02-15,2024-02-15,2779.150576,2858.699668,2768.714837,2825.427733,8.396383e+06,1.0,1310.0,1189.0,4.430020e+06,3.966363e+06,1,19229631,19236753,NaN
2024-02-16,2024-02-16,2825.453348,2853.931311,2762.504946,2805.197421,5.831365e+06,1.0,1430.0,1138.0,2.821308e+06,3.010057e+06,1,19236756,19243884,NaN
2024-02-17,2024-02-17,2805.268248,2806.289102,2728.880763,2790.545222,4.320961e+06,1.0,1331.0,1080.0,2.091628e+06,2.229333e+06,1,19243885,19250997,NaN
2024-02-18,2024-02-18,2790.441882,2889.331794,2772.053190,2876.579808,6.022618e+06,1.0,1648.0,1147.0,3.433857e+06,2.588761e+06,1,19251000,19258090,NaN
2024-02-19,2024-02-19,2876.621219,2983.602749,2865.791859,2941.293499,8.459049e+06,1.0,1744.0,1382.0,4.546358e+06,3.912691e+06,1,19258094,19265202,NaN
2024-02-20,2024-02-20,2941.450313,3023.779313,2886.872809,3014.982081,9.608266e+06,1.0,1794.0,1355.0,5.160903e+06,4.447363e+06,1,19265206,19272339,NaN
2024-02-21,2024-02-21,3014.984596,3018.399585,2879.668227,2972.668140,8.723001e+06,1.0,1432.0,1183.0,4.167912e+06,4.555089e+06,1,19272342,19279446,NaN
2024-02-22,2024-02-22,2972.878404,3023.161327,2912.345442,2974.979868,9.333684e+06,1.0,1385.0,1044.0,4.684849e+06,4.648835e+06,1,19279462,19286572,NaN
2024-02-23,2024-02-23,2975.141667,2987.234236,2912.244077,2920.711620,7.094898e+06,1.0,1702.0,1078.0,3.293882e+06,3.801016e+06,1,19286587,19293721,NaN
2024-02-24,2024-02-24,2920.689258,3005.529469,2913.737345,2994.864738,5.027131e+06,1.0,1531.0,1109.0,2.870631e+06,2.156500e+06,1,19293724,19300879,NaN
2024-02-25,2024-02-25,2994.687278,3114.869972,2991.544058,3112.578810,5.803871e+06,1.0,1480.0,1146.0,3.458335e+06,2.345535e+06,1,19300884,19308029,NaN
2024-01-30,2024-01-30,2316.505918,2389.677515,2297.129731,2344.235617,5.023445e+07,1.0,NaN,NaN,NaN,NaN,2991521,175542107,175877916,NaN
2024-01-31,2024-01-31,2344.001217,2350.103244,2264.289721,2282.932294,6.258897e+07,1.0,NaN,NaN,NaN,NaN,2991521,175878016,176212277,NaN
2024-02-01,2024-02-01,2282.932294,2309.798117,2243.106175,2302.879452,4.802019e+07,1.0,NaN,NaN,NaN,NaN,2991521,176212567,176539843,NaN
2024-02-02,2024-02-02,2302.879452,2322.304138,2282.019350,2307.028160,3.221227e+07,1.0,NaN,NaN,NaN,NaN,2991521,176539905,176864132,NaN
2024-02-03,2024-02-03,2307.028160,2326.720489,2292.769546,2294.374966,1.446643e+07,1.0,NaN,NaN,NaN,NaN,2991521,176864193,177184194,NaN
2024-02-04,2024-02-04,2294.374966,2308.412723,2269.276392,2289.333142,2.536486e+07,1.0,NaN,NaN,NaN,NaN,2991521,177184200,177507320,NaN
2024-02-05,2024-02-05,2289.333142,2335.111358,2269.049487,2297.818939,3.152637e+07,1.0,NaN,NaN,NaN,NaN,2991521,177507460,177837755,NaN
2024-02-06,2024-02-06,2297.818939,2388.960755,2296.670374,2372.060047,4.418362e+07,1.0,NaN,NaN,NaN,NaN,2991521,177838037,178165992,NaN
2024-02-07,2024-02-07,2372.060047,2442.097597,2353.160212,2423.851286,3.624003e+07,1.0,NaN,NaN,NaN,NaN,2991521,178166487,178500560,NaN
2024-02-08,2024-02-08,2423.851286,2461.465602,2412.486482,2420.944555,4.050429e+07,1.0,NaN,NaN,NaN,NaN,2991521,178500795,178830373,NaN
2024-02-09,2024-02-09,2420.944555,2522.008810,2419.976419,2487.694594,6.655769e+07,1.0,NaN,NaN,NaN,NaN,2991521,178830460,179152221,NaN
2024-02-10,2024-02-10,2487.694594,2515.711978,2474.297917,2500.663648,2.892087e+07,1.0,NaN,NaN,NaN,NaN,2991521,179152294,179482630,NaN
2024-02-11,2024-02-11,2500.663648,2539.216048,2495.667568,2506.922815,3.395467e+07,1.0,NaN,NaN,NaN,NaN,2991521,179482820,179816688,NaN
2024-02-12,2024-02-12,2507.173507,2664.863871,2473.803132,2658.476186,5.958445e+07,1.0,NaN,NaN,NaN,NaN,2991521,179816691,180150106,NaN
2024-02-13,2024-02-13,2659.539736,2687.073172,2593.619346,2641.517113,6.292276e+07,1.0,NaN,NaN,NaN,NaN,2991521,180150222,180487998,NaN
2024-02-14,2024-02-14,2641.517113,2788.351919,2621.256547,2777.499066,5.349098e+07,1.0,NaN,NaN,NaN,NaN,2991521,180488538,180823639,NaN
2024-02-15,2024-02-15,2777.499066,2868.098600,2763.923287,2823.988017,7.047362e+07,1.0,NaN,NaN,NaN,NaN,2991521,180823771,181157523,NaN
2024-02-16,2024-02-16,2823.988017,2858.364109,2757.298156,2804.570538,5.334966e+07,1.0,NaN,NaN,NaN,NaN,2991521,181157598,181491834,NaN
2024-02-17,2024-02-17,2804.570538,2805.131480,2722.231399,2786.679493,3.289069e+07,1.0,NaN,NaN,NaN,NaN,2991521,181491925,181824237,NaN
2024-02-18,2024-02-18,2786.679493,2894.316095,2767.795296,2879.881353,4.528268e+07,1.0,NaN,NaN,NaN,NaN,2991521,181824345,182158245,NaN
2024-02-19,2024-02-19,2879.881353,2983.351496,2858.364109,2943.643211,5.773708e+07,1.0,NaN,NaN,NaN,NaN,2991521,182158269,182490788,NaN
2024-02-20,2024-02-20,2943.643211,3047.879984,2875.564985,3014.237260,9.167801e+07,1.0,NaN,NaN,NaN,NaN,2991521,182490871,182827175,NaN
2024-02-21,2024-02-21,3014.237260,3015.744680,2869.532936,2968.769557,8.710820e+07,1.0,NaN,NaN,NaN,NaN,2991521,182827354,183160983,NaN
2024-02-22,2024-02-22,2968.175892,3034.802889,2907.950715,2969.660277,7.191654e+07,1.0,NaN,NaN,NaN,NaN,2991521,183161038,183491432,NaN
2024-02-23,2024-02-23,2969.660277,2990.818831,2907.659949,2922.233925,4.220740e+07,1.0,NaN,NaN,NaN,NaN,2991521,183491555,183818224,NaN
2024-02-24,2024-02-24,2922.233925,3004.908059,2907.659949,2991.716167,2.089115e+07,1.0,NaN,NaN,NaN,NaN,2991521,183818489,184150610,NaN
2024-02-25,2024-02-25,2992.015338,3121.910211,2984.843470,3111.003169,3.270970e+07,1.0,NaN,NaN,NaN,NaN,2991521,184150629,184485523,NaN